### PR TITLE
add typescript type information

### PR DESCRIPTION
**Pull request by MrPechi**
just a typescript definition, this could be useful to typescript developers

### CODE REVIEW

**Comment by marudy** [comment]
Thanks a lot for the PR @MrPechi. I have been thinking to add it for some time as well.

Did you test locally first to verify that `tsc` does no longer complain indeed?

**Comment by MrPechi** [comment]
Yeh, I'd tested with typescript 3. So I used it in a react-native (v0.57) project with Component and PureComponent classes. All working fine here

**Comment by marudy** [comment]
Thanks again @MrPechi, merging and releasing now :)

**Comment by marudy** [comment]
@MrPechi it's done, it's published in v1.2.0

**Pull request merged**
